name: Pull Request Workflow
on: 
  pull_request:
    branches:
      - 'master'
      - 'production'

jobs:
  test-nautowired-console:
    name: test nautowired console
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: NAutowired.Console.Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: "dotnet test NAutowired.Console.Test.csproj"
        name: 'Unit Test'
